### PR TITLE
domain indexer refactoring, ops status, todo cleanup

### PR DESCRIPTION
**Pull request by manigandham**
- Added `DomainStore` for extensible lookup/store operations of domain info.
- Refactored counterparty manager into `DomainIndexer` component that accepts a (default) `DnsResolver` and (default) `DomainStore` as components to lookup dns entries and manage shared secrets generation.
- API definition and format structs have been updated with new `SignatureStatus`, `VerificationStatus`, `AuthenticatedConnectionProtocolStatus` to passthrough operation status as much as possible. Future cleanup still needed as most status flags are set to OK or Error for now.
- All other MVP "todos" are completed, and other features have been extracted and documented separately. Will be entered as Github issues for public tracking.

### CODE REVIEW

**Comment by manigandham** [comment]
Hey @cmlight 
Another big refactor to cleanup the counterparty management. This should get us to a polished MVP status, with the remaining tasks being loading the private keys (I'll update the samples and dockerfile) and reading a JSON file to seed domain lookups.

**Comment by grossjo** [comment]
This seems like a decent refactor. Any added tests needed for the new split out components?

**Comment by manigandham** [comment]
The existing tests already check the various formats (auth conn signature, policy record, key record) and signature/verification outcomes. We can add more once I finish the documentation after this is merged.

**Review by cmlight — APPROVED** [review]
Thanks for working on this refactoring!  Looks good

**Pull request merged**
